USE [PROJECT]
GO

/****** Object:  Table [dbo].[DEBT]    Script Date: 12.08.2024 19:51:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEBT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COUNTRYNAME] [varchar](50) NULL,
	[COUNTRYCODE] [varchar](10) NULL,
	[INDICATORNAME] [varchar](max) NULL,
	[INDICATORCODE] [varchar](50) NULL,
	[DEBT] [money] NULL,
 CONSTRAINT [PK_DEBT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


