
--THE HIGHEST AMOUNT OF PRINCIPAL REPAYMENTS

SELECT 

COUNTRYNAME, INDICATORCODE, INDICATORNAME, AVG(DEBT) AS AVERAGE_DEBT

FROM DEBT

GROUP BY COUNTRYNAME, INDICATORCODE, INDICATORNAME

HAVING INDICATORCODE='DT.AMT.DLXF.CD'

ORDER BY AVG(DEBT) DESC