
--THE MOST COMMON DEBT INDICATOR

SELECT 

INDICATORCODE, INDICATORNAME, COUNT(INDICATORCODE) AS INDICATOR_COUNT

FROM DEBT

GROUP BY INDICATORCODE, INDICATORNAME

ORDER BY COUNT(INDICATORCODE) DESC

